-- !Ups
CREATE TABLE "USERS" (
  "ID" UUID,
  "NAME" VARCHAR,
  "EMAIL" VARCHAR UNIQUE,
  "USERNAME" VARCHAR UNIQUE,
  "PASSWORD" VARCHAR,
  "AVATAR" VARCHAR,
  PRIMARY KEY ("ID")
);

CREATE TABLE "FILES" (
  "ID" UUID,
  "NAME" VARCHAR,
  "PATH" VARCHAR,
  "IDUSER" UUID
);

-- !Downs
DROP TABLE "USERS";
DROP TABLE "FILES";
